server:
  port: 8080

spring:
  profiles:
    active: @env@
  application:
    name: Crazy-Kart-Club
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/club?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    serialization:
      write-dates-as-timestamps: true
  freemarker:
    settings:
      auto_import: common/all.ftl as ca
      template_update_delay: 0
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_format: HH:mm:ss
    request-context-attribute: rca
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: vip.crazykart.model
  config-location: classpath:mybatis.xml

mapper:
  mappers: com.kangyonggan.common.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

logging:
  config: classpath:env/@env@/log4j2.xml


